name: "Test outputs on commit"
on:
  pull_request:
  push:
    branches:
      - master

jobs:

  tests:
    name: "TestsOnCommits"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
    
      - name: Install Forta dependencies
        working-directory: ./maker_dao
        shell: bash
        run: npm install
    
      - name: Run tests
        working-directory: ./maker_dao
        shell: bash
        run: npm run test
